# Generated by Django 2.2.4 on 2019-09-07 08:38

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='body',
            field=markupfield.fields.MarkupField(blank=True, rendered_field=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='body_markup_type',
            field=models.CharField(blank=True, choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown'), ('restructuredtext', 'Restructured Text')], default=None, max_length=30, null=True),
        ),
    ]
