# Generated by Django 2.2.4 on 2019-09-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190907_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='end',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='start',
        ),
        migrations.AlterField(
            model_name='item',
            name='body_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown'), ('restructuredtext', 'Restructured Text')], default='markdown', max_length=30),
        ),
    ]
