# Generated by Django 2.2.4 on 2019-08-08 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190808_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationery',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.Category'),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='image',
            field=models.ImageField(null=True, upload_to='stationeries/%Y/%m/%d'),
        ),
    ]
