# Generated by Django 2.2.4 on 2019-08-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190808_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationery',
            name='vendor_code',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
