# Generated by Django 2.2.4 on 2019-08-08 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190808_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationery',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.Category'),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stationeries/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
