# Generated by Django 2.2.4 on 2019-08-08 12:20

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20190808_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationery',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='KZT', max_digits=19),
        ),
    ]
