# Generated by Django 2.2.4 on 2019-08-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_auto_20190827_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='body_markup_type',
            field=models.CharField(blank=True, choices=[('', '--'), ('markdown', 'markdown'), ('rest', 'rest')], default=None, max_length=30, null=True),
        ),
    ]
