# Generated by Django 2.2.4 on 2019-08-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_auto_20190827_0210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ('-created',)},
        ),
    ]
